spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    url: jdbc:sqlserver://localhost;database=HumanResource
    username: qst
    password: qst123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis:
  mapper-locations: mapper/*.xml
sensor:
  port: 8080
  dataLength: 27
server:
  port: 8080